version: "3"

services:
  app:
    image: thakkaryash94/express-example:latest
    container_name: express-app
    ports:
      - "4000:3000"
    logging:
      driver: fluentd
      options:
        fluentd-address: FLUENT_BIT_ADDRESS:24224
